[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
<<<<<<< HEAD
disable_error_code = no-any-return,arg-type,assignment,misc,attr-defined,index,import-untyped
=======
follow_imports = skip
disable_error_code = no-any-return,arg-type,assignment,misc,attr-defined,index
>>>>>>> backup/local-before-sync

[mypy-torch.*]
ignore_errors = True

[mypy-tests.*]
disallow_untyped_defs = False
